### ISSUE TITLE
multimarkdown comments

### ISSUE THREAD

**Issue by danielb2** [fletcher/MultiMarkdown#41]
One thing which both HTML and LaTeX allows is commenting. This is a useful feature when authoring longer pieces of text as it allows the author to make notes about the text.  Is it possible? I've tried <!-- which doesn't work.

**Comment by fletcher** [comment]
I'm responding because I like your avatar icon....  ;)

This particular project is mothballed, as indicated on the README.  It was replaced by MMD 3, which has since been replaced by MMD 4. (So the Perl version is really out of date...)

HTML comments are used to insert raw text without processing it for MMD syntax (useful for entering raw LaTeX for example.)

MMD 4 supports CriticMarkup, which has it's own syntax for comments ---  {>>foo<<}

Future issues will be better addressed in an active project.  General questions are probably best sent to the MMD Discussion List.

http://fletcherpenney.net/multimarkdown/help/

**Comment by danielb2** [comment]
Thanks ;)

**Comment by danielb2** [comment]
Oh, and just in case someone didn't glean this from this issue... currently be able to comment for LaTeX generation (which is what I was using this for ) you can do:

```
<!--
% this text will be
% commented out
-->
```
