### ISSUE TITLE
CSS file relative path

### ISSUE THREAD

**Issue by sibinpthomas** [fletcher/MultiMarkdown#47]
It would be best if the relative path of the CSS file mentioned in the metadata is relative to the input file (i.e. Markdown file) instead of the output file (i.e. HTML file).

This would make it easier to chain this program with other programs.
I am specifically concerned with this issue - 
https://github.com/swaroopch/vim-markdown-preview/issues/6

**Comment by fletcher** [comment]
I'm not sure I understand.  You want me to rewrite your browser's code so that instead of using a relative CSS path based on the file you're viewing (e.g. the HTML file), you want me to instead base that relative path on a separate file (e.g. the original markdown text file), that the browser doesn't even know exists and may or may not even be around at the time the HTML file is used????  Do you want me to do the same thing for images, URLs, links to script files, etc.???

I believe if you think about this further, you'll realize it doesn't make sense.  If you're having a problem with your web browser (or other HTML preview code) and relative file paths, the way to fix that is to fix the HTML previewer.  It's not to change MultiMarkdown.

As far as MMD is concerned, whether a path is relative or absolute, or whether the specified file even exists is irrelevant.  It passes along whatever you specify to the HTML file.  It's the HTML viewer program's job to correctly calculate absolute paths from relative paths, and by definition these relative paths are based of the location of the HTML file.

If the other tools in your toolchain are not working properly, you need to address that with the appropriate developers or stick with absolute file paths.

**Comment by sibinpthomas** [comment]
Let me try and help you understand the issue.

This is roughly my repo folder structure :

```
    |- Source
    |   |- epic_novel.md
    |   |- storyboard.md
    |- Style
    |   |- classic_novel_foofy.css
    |   |- classic_novel_scary.css
    |   |- table_1.css
    |   |- table_bold.css
```

As I write my novel and keep tweaking my storyboard I need to repeatedly preview the Markdown file just to make sure that the generated HTML looks the way I think it should. I use a Markdown Preview VIM plugin (https://github.com/swaroopch/vim-markdown-preview) to quickly check the HTML file that is generated from the Markdown file I am working on. This plugin just dumbly calls the MMD executable (as it should) and directs the generated HTML file into some temporary folder (background detail) and opens the HTML file in the default browser.

Given this, some of the ways we can achieve the desired outcome would be :

a. You could have a separate mode to base relative paths off the source file (.md) instead of the generated file (.html).

   MMD reads the relative path of the CSS file and converts it into an absolute path while adding the CSS path string in the HTML header.
   That is,
       You see this (in storyboard.md) -

```
           CSS: ..\Style\table_bold.css  
```

and generate this -

```
           <!DOCTYPE html>
           <html>
           <head>
               <meta charset="utf-8"/>
               <link type="text/css" rel="stylesheet" href="E:\some_dir\My_Novel\Style\table_bold.css"/>
           </head>
           <body>
```

b. MMD reads the CSS file and directly adds the style information into the HTML header.  
   That is,  
       You see this (in storyboard.md) -  

```
           CSS: ..\Style\table_bold.css  
```

and generate this -  

```
           <!DOCTYPE html>
           <html>
           <head>
               <meta charset="utf-8"/>
           <style type="text/css" media="all" >
           caption { font-size: 200%;}table   { border: 1px solid black; }td,th   { border: 1px solid black; }th      { width: 120px; }</style>
           </head>
           <body>
```

c. MMD could copy the CSS file into output folder (thereby creating a duplicate). That is you don't just generate a HTML file but an entire folder with the HTML file, CSS and image files etc. in it.  

Surely there are other ways to work around this problem (e.g. the preview plugin could generate the HTML file in the same folder as the Markdown source file), but I would like it if you could incorporate either of the suggestions. I personally prefer option (a), it is an enhancement which doesn't (at least, shoudn't) affect any of the existing functionalities.

**Comment by fletcher** [comment]
No, I understood you. The problem is still with your previewer, not with MultiMarkdown. If the previewer creates a temporary HTML file, it needs to properly account for relative paths.  

MultiMarkdown Composer handles this problem just fine, for example.
